name: 'Deploy to AWS S3 (docker)'
description: 'Deploy a static website via AWS S3.'
inputs:
  bucket:
    description: 'Bucket name'
    required: true
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
outputs:
  website-url:
    description: 'The Url of a website'
runs:
  using: 'docker'
  image: 'Dockerfile'